<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>01-Unbiased_transmission.split</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown #bookdown:version# and GitBook 2.6.7" />

  <meta property="og:title" content="01-Unbiased_transmission.split" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="01-Unbiased_transmission.split" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<!--bookdown:link_prev-->
<!--bookdown:link_next-->
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



<!--bookdown:title:start-->
<!--bookdown:title:end-->

<!--bookdown:toc:start-->
  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">
<!--bookdown:toc2:start-->
<ul>
<li><a href="#part-basics">(PART*) Basics</a><ul>
<li><a href="#initialising-the-simulation"><span class="toc-section-number">0.1</span> Initialising the simulation</a></li>
<li><a href="#execute-generation-turn-over-many-times"><span class="toc-section-number">0.2</span> Execute generation turn-over many times</a></li>
<li><a href="#plotting-the-model-results"><span class="toc-section-number">0.3</span> Plotting the model results</a></li>
<li><a href="#write-a-function-to-wrap-the-model-code"><span class="toc-section-number">0.4</span> Write a function to wrap the model code</a></li>
<li><a href="#run-several-independent-simulations-and-plot-their-results"><span class="toc-section-number">0.5</span> Run several independent simulations and plot their results</a></li>
<li><a href="#varying-initial-conditions"><span class="toc-section-number">0.6</span> Varying initial conditions</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">0.7</span> Summary of the model</a></li>
<li><a href="#further-reading"><span class="toc-section-number">0.8</span> Further reading</a></li>
</ul></li>
<li><a href="#unbiased-and-biased-mutation"><span class="toc-section-number">1</span> Unbiased and biased mutation</a><ul>
<li><a href="#unbiased-mutation"><span class="toc-section-number">1.1</span> Unbiased mutation</a></li>
<li><a href="#biased-mutation"><span class="toc-section-number">1.2</span> Biased mutation</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">1.3</span> Summary of the model</a></li>
<li><a href="#further-reading"><span class="toc-section-number">1.4</span> Further reading</a></li>
</ul></li>
<li><a href="#biased-transmission-direct-bias"><span class="toc-section-number">2</span> Biased transmission: direct bias</a><ul>
<li><a href="#a-simple-model-of-directly-biased-transmission"><span class="toc-section-number">2.1</span> A simple model of directly biased transmission</a></li>
<li><a href="#strength-of-selection"><span class="toc-section-number">2.2</span> Strength of selection</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">2.3</span> Summary of the model</a></li>
<li><a href="#further-reading"><span class="toc-section-number">2.4</span> Further reading</a></li>
</ul></li>
<li><a href="#biased-transmission-frequency-dependent-indirect-bias"><span class="toc-section-number">3</span> Biased transmission: frequency-dependent indirect bias</a><ul>
<li><a href="#the-logic-of-conformity"><span class="toc-section-number">3.1</span> The logic of conformity</a></li>
<li><a href="#testing-conformist-transmission"><span class="toc-section-number">3.2</span> Testing conformist transmission</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">3.3</span> Summary of the model</a></li>
<li><a href="#further-readings"><span class="toc-section-number">3.4</span> Further readings</a></li>
</ul></li>
<li><a href="#biased-transmission-demonstrator-based-indirect-bias"><span class="toc-section-number">4</span> Biased transmission: demonstrator-based indirect bias</a><ul>
<li><a href="#a-simple-demonstrator-bias"><span class="toc-section-number">4.1</span> A simple demonstrator bias</a></li>
<li><a href="#predicting-the-winning-trait"><span class="toc-section-number">4.2</span> Predicting the ‘winning’ trait</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">4.3</span> Summary of the model</a></li>
<li><a href="#further-readings"><span class="toc-section-number">4.4</span> Further readings</a></li>
</ul></li>
<li><a href="#vertical-and-horizontal-transmission"><span class="toc-section-number">5</span> Vertical and horizontal transmission</a><ul>
<li><a href="#vertical-cultural-transmission"><span class="toc-section-number">5.1</span> Vertical cultural transmission</a></li>
<li><a href="#horizontal-cultural-transmission"><span class="toc-section-number">5.2</span> Horizontal cultural transmission</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">5.3</span> Summary of the model</a></li>
<li><a href="#further-reading"><span class="toc-section-number">5.4</span> Further reading</a></li>
</ul></li>
<li><a href="#multiple-traits-models"><span class="toc-section-number">6</span> Multiple traits models</a><ul>
<li><a href="#unbiased-transmission-with-multiple-traits"><span class="toc-section-number">6.1</span> Unbiased transmission with multiple traits</a></li>
<li><a href="#introducing-innovation"><span class="toc-section-number">6.2</span> Introducing innovation</a></li>
<li><a href="#optimising-the-code"><span class="toc-section-number">6.3</span> Optimising the code</a></li>
<li><a href="#the-distribution-of-popularity"><span class="toc-section-number">6.4</span> The distribution of popularity</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">6.5</span> Summary of the model</a></li>
<li><a href="#further-readings"><span class="toc-section-number">6.6</span> Further readings</a></li>
</ul></li>
<li><a href="#part-advanced-topics---the-evolution-of-cultural-evolution">(PART*) Advanced topics - The evolution of cultural evolution</a><ul>
<li><a href="#modelling-rogers-paradox"><span class="toc-section-number">6.7</span> Modelling Rogers’ Paradox</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">6.8</span> Summary of the model</a></li>
<li><a href="#further-reading"><span class="toc-section-number">6.9</span> Further reading</a></li>
</ul></li>
<li><a href="#rogers-paradox-a-solution"><span class="toc-section-number">7</span> Rogers’ Paradox: A Solution</a><ul>
<li><a href="#modelling-critical-social-learners"><span class="toc-section-number">7.1</span> Modelling critical social learners</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">7.2</span> Summary of the model</a></li>
<li><a href="#further-reading"><span class="toc-section-number">7.3</span> Further reading</a></li>
</ul></li>
<li><a href="#part-advanced-topics---culture-and-populations">(PART*) Advanced topics - Culture and populations</a></li>
<li><a href="#demography"><span class="toc-section-number">8</span> Demography</a><ul>
<li><a href="#background-on-demography-mediated-cultural-loss"><span class="toc-section-number">8.1</span> Background on demography-mediated cultural loss</a></li>
<li><a href="#the-tasmania-case-model"><span class="toc-section-number">8.2</span> The Tasmania Case model</a><ul>
<li><a href="#modelling-the-tasmania-case"><span class="toc-section-number">8.2.1</span> Modelling the Tasmania Case</a></li>
<li><a href="#calculating-critical-population-sizes-based-on-skill-complexity"><span class="toc-section-number">8.2.2</span> Calculating critical population sizes based on skill complexity</a></li>
</ul></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">8.3</span> Summary of the model</a></li>
<li><a href="#further-readings"><span class="toc-section-number">8.4</span> Further readings</a></li>
</ul></li>
<li><a href="#social-network-structure"><span class="toc-section-number">9</span> Social network structure</a><ul>
<li><a href="#network-basics"><span class="toc-section-number">9.1</span> Network basics</a></li>
<li><a href="#plotting-networks"><span class="toc-section-number">9.2</span> Plotting networks</a></li>
<li><a href="#analyse-social-networks"><span class="toc-section-number">9.3</span> Analyse social networks</a><ul>
<li><a href="#network-properties"><span class="toc-section-number">9.3.1</span> Network properties</a></li>
<li><a href="#vertex-properties"><span class="toc-section-number">9.3.2</span> Vertex properties</a></li>
</ul></li>
<li><a href="#using-social-networks-to-model-information-transmission"><span class="toc-section-number">9.4</span> Using social networks to model information transmission</a><ul>
<li><a href="#gossip-transmission-on-networked-populations"><span class="toc-section-number">9.4.1</span> Gossip transmission on networked populations</a></li>
<li><a href="#how-does-network-structure-affect-information-transmission"><span class="toc-section-number">9.4.2</span> How does network structure affect information transmission?</a></li>
<li><a href="#complex-versus-simple-contagion"><span class="toc-section-number">9.4.3</span> Complex versus simple contagion</a></li>
</ul></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">9.5</span> Summary of the model</a></li>
<li><a href="#further-reading"><span class="toc-section-number">9.6</span> Further Reading</a></li>
</ul></li>
<li><a href="#group-structured-populations-and-migration"><span class="toc-section-number">10</span> Group structured populations and migration</a><ul>
<li><a href="#modelling-migration"><span class="toc-section-number">10.1</span> Modelling migration</a></li>
<li><a href="#subdivided-population"><span class="toc-section-number">10.2</span> Subdivided population</a></li>
<li><a href="#simulating-migration-between-sub-populations"><span class="toc-section-number">10.3</span> Simulating migration between sub-populations</a></li>
<li><a href="#varying-the-strength-of-migration-for-repeated-simulation-runs"><span class="toc-section-number">10.4</span> Varying the strength of migration for repeated simulation runs</a></li>
<li><a href="#model-extensions"><span class="toc-section-number">10.5</span> Model extensions</a><ul>
<li><a href="#innovation-or-mutation">Innovation or mutation</a></li>
<li><a href="#copy-m-models">Copy <span class="math inline">\(m\)</span> models</a></li>
<li><a href="#learn-from-but-not-moving-to-another-sub-population">Learn from but not moving to another sub-population</a></li>
<li><a href="#variable-migration-probability-among-sub-populations">Variable migration probability among sub-populations</a></li>
</ul></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">10.6</span> Summary of the model</a></li>
<li><a href="#further-reading"><span class="toc-section-number">10.7</span> Further reading</a></li>
</ul></li>
<li><a href="#part-advanced-topics---cultural-inheritance">(PART*) Advanced topics - Cultural inheritance</a><ul>
<li><a href="#copying-and-selection"><span class="toc-section-number">10.8</span> Copying and selection</a></li>
<li><a href="#convergent-transformation"><span class="toc-section-number">10.9</span> Convergent transformation</a></li>
<li><a href="#emergent-similarity"><span class="toc-section-number">10.10</span> Emergent similarity</a></li>
<li><a href="#cultural-fitness"><span class="toc-section-number">10.11</span> Cultural fitness</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">10.12</span> Summary of the model</a></li>
<li><a href="#further-readings"><span class="toc-section-number">10.13</span> Further readings</a></li>
</ul></li>
<li><a href="#social-learning-of-social-learning-rules"><span class="toc-section-number">11</span> Social learning of social learning rules</a><ul>
<li><a href="#openness-and-conservatism"><span class="toc-section-number">11.1</span> Openness and conservatism</a></li>
<li><a href="#maintaining-open-populations"><span class="toc-section-number">11.2</span> Maintaining open populations</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">11.3</span> Summary of the model</a></li>
<li><a href="#further-readings"><span class="toc-section-number">11.4</span> Further readings</a></li>
</ul></li>
<li><a href="#traits-inter-dependence"><span class="toc-section-number">12</span> Traits inter-dependence</a><ul>
<li><a href="#compatible-and-incompatible-traits"><span class="toc-section-number">12.1</span> Compatible and incompatible traits</a></li>
<li><a href="#many-traits-model"><span class="toc-section-number">12.2</span> Many-traits model</a></li>
<li><a href="#summary-of-the-model"><span class="toc-section-number">12.3</span> Summary of the model</a></li>
<li><a href="#further-readings"><span class="toc-section-number">12.4</span> Further readings</a></li>
</ul></li>
<li><a href="#Introduction">Introduction</a><ul>
<li><a href="#aim-of-the-book"><span class="toc-section-number">12.5</span> Aim of the book</a></li>
<li><a href="#what-is-cultural-evolution"><span class="toc-section-number">12.6</span> What is cultural evolution?</a></li>
<li><a href="#why-model"><span class="toc-section-number">12.7</span> Why model?</a></li>
<li><a href="#why-individual-based-models"><span class="toc-section-number">12.8</span> Why individual-based models?</a></li>
<li><a href="#how-to-use-this-book"><span class="toc-section-number">12.9</span> How to use this book</a></li>
<li><a href="#conventions-and-formatting"><span class="toc-section-number">12.10</span> Conventions and formatting</a></li>
</ul></li>
</ul>
<!--bookdown:toc2:end-->
      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!--bookdown:toc:end-->
<!--bookdown:body:start-->
<div id="part-basics" class="section level1 unnumbered">
<h1>(PART*) Basics</h1>
<p>Placeholder</p>
<div id="initialising-the-simulation" class="section level2">
<h2><span class="header-section-number">0.1</span> Initialising the simulation</h2>
</div>
<div id="execute-generation-turn-over-many-times" class="section level2">
<h2><span class="header-section-number">0.2</span> Execute generation turn-over many times</h2>
</div>
<div id="plotting-the-model-results" class="section level2">
<h2><span class="header-section-number">0.3</span> Plotting the model results</h2>
</div>
<div id="write-a-function-to-wrap-the-model-code" class="section level2">
<h2><span class="header-section-number">0.4</span> Write a function to wrap the model code</h2>
</div>
<div id="run-several-independent-simulations-and-plot-their-results" class="section level2">
<h2><span class="header-section-number">0.5</span> Run several independent simulations and plot their results</h2>
</div>
<div id="varying-initial-conditions" class="section level2">
<h2><span class="header-section-number">0.6</span> Varying initial conditions</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">0.7</span> Summary of the model</h2>
</div>
<div id="further-reading" class="section level2">
<h2><span class="header-section-number">0.8</span> Further reading</h2>
<!--chapter:end:01-Unbiased_transmission.Rmd-->
</div>
</div>
<div id="unbiased-and-biased-mutation" class="section level1">
<h1><span class="header-section-number">1</span> Unbiased and biased mutation</h1>
<p>Placeholder</p>
<div id="unbiased-mutation" class="section level2">
<h2><span class="header-section-number">1.1</span> Unbiased mutation</h2>
</div>
<div id="biased-mutation" class="section level2">
<h2><span class="header-section-number">1.2</span> Biased mutation</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">1.3</span> Summary of the model</h2>
</div>
<div id="further-reading" class="section level2">
<h2><span class="header-section-number">1.4</span> Further reading</h2>
<!--chapter:end:02-Unbiased_and_biased_mutation.Rmd-->
</div>
</div>
<div id="biased-transmission-direct-bias" class="section level1">
<h1><span class="header-section-number">2</span> Biased transmission: direct bias</h1>
<p>Placeholder</p>
<div id="a-simple-model-of-directly-biased-transmission" class="section level2">
<h2><span class="header-section-number">2.1</span> A simple model of directly biased transmission</h2>
</div>
<div id="strength-of-selection" class="section level2">
<h2><span class="header-section-number">2.2</span> Strength of selection</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">2.3</span> Summary of the model</h2>
</div>
<div id="further-reading" class="section level2">
<h2><span class="header-section-number">2.4</span> Further reading</h2>
<!--chapter:end:03-Biased_transmission_direct_bias.Rmd-->
</div>
</div>
<div id="biased-transmission-frequency-dependent-indirect-bias" class="section level1">
<h1><span class="header-section-number">3</span> Biased transmission: frequency-dependent indirect bias</h1>
<p>Placeholder</p>
<div id="the-logic-of-conformity" class="section level2">
<h2><span class="header-section-number">3.1</span> The logic of conformity</h2>
</div>
<div id="testing-conformist-transmission" class="section level2">
<h2><span class="header-section-number">3.2</span> Testing conformist transmission</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">3.3</span> Summary of the model</h2>
</div>
<div id="further-readings" class="section level2">
<h2><span class="header-section-number">3.4</span> Further readings</h2>
<!--chapter:end:04-Biased_transmission_indirect_bias_frequency.Rmd-->
</div>
</div>
<div id="biased-transmission-demonstrator-based-indirect-bias" class="section level1">
<h1><span class="header-section-number">4</span> Biased transmission: demonstrator-based indirect bias</h1>
<p>Placeholder</p>
<div id="a-simple-demonstrator-bias" class="section level2">
<h2><span class="header-section-number">4.1</span> A simple demonstrator bias</h2>
</div>
<div id="predicting-the-winning-trait" class="section level2">
<h2><span class="header-section-number">4.2</span> Predicting the ‘winning’ trait</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">4.3</span> Summary of the model</h2>
</div>
<div id="further-readings" class="section level2">
<h2><span class="header-section-number">4.4</span> Further readings</h2>
<!--chapter:end:05-Biased_transmission_indirect_bias_demonstrator.Rmd-->
</div>
</div>
<div id="vertical-and-horizontal-transmission" class="section level1">
<h1><span class="header-section-number">5</span> Vertical and horizontal transmission</h1>
<p>Placeholder</p>
<div id="vertical-cultural-transmission" class="section level2">
<h2><span class="header-section-number">5.1</span> Vertical cultural transmission</h2>
</div>
<div id="horizontal-cultural-transmission" class="section level2">
<h2><span class="header-section-number">5.2</span> Horizontal cultural transmission</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">5.3</span> Summary of the model</h2>
</div>
<div id="further-reading" class="section level2">
<h2><span class="header-section-number">5.4</span> Further reading</h2>
<!--chapter:end:06-Vertical_horizontal_transmission.Rmd-->
</div>
</div>
<div id="multiple-traits-models" class="section level1">
<h1><span class="header-section-number">6</span> Multiple traits models</h1>
<p>Placeholder</p>
<div id="unbiased-transmission-with-multiple-traits" class="section level2">
<h2><span class="header-section-number">6.1</span> Unbiased transmission with multiple traits</h2>
</div>
<div id="introducing-innovation" class="section level2">
<h2><span class="header-section-number">6.2</span> Introducing innovation</h2>
</div>
<div id="optimising-the-code" class="section level2">
<h2><span class="header-section-number">6.3</span> Optimising the code</h2>
</div>
<div id="the-distribution-of-popularity" class="section level2">
<h2><span class="header-section-number">6.4</span> The distribution of popularity</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">6.5</span> Summary of the model</h2>
</div>
<div id="further-readings" class="section level2">
<h2><span class="header-section-number">6.6</span> Further readings</h2>
<!--chapter:end:07-Multiple_traits_models.Rmd-->
</div>
</div>
<div id="part-advanced-topics---the-evolution-of-cultural-evolution" class="section level1 unnumbered">
<h1>(PART*) Advanced topics - The evolution of cultural evolution</h1>
<p>Placeholder</p>
<div id="modelling-rogers-paradox" class="section level2">
<h2><span class="header-section-number">6.7</span> Modelling Rogers’ Paradox</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">6.8</span> Summary of the model</h2>
</div>
<div id="further-reading" class="section level2">
<h2><span class="header-section-number">6.9</span> Further reading</h2>
<!--chapter:end:08-Rogers_paradox.Rmd-->
</div>
</div>
<div id="rogers-paradox-a-solution" class="section level1">
<h1><span class="header-section-number">7</span> Rogers’ Paradox: A Solution</h1>
<p>Placeholder</p>
<div id="modelling-critical-social-learners" class="section level2">
<h2><span class="header-section-number">7.1</span> Modelling critical social learners</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">7.2</span> Summary of the model</h2>
</div>
<div id="further-reading" class="section level2">
<h2><span class="header-section-number">7.3</span> Further reading</h2>
<!--chapter:end:09-Rogers_solution.Rmd-->
</div>
</div>
<div id="part-advanced-topics---culture-and-populations" class="section level1 unnumbered">
<h1>(PART*) Advanced topics - Culture and populations</h1>
</div>
<div id="demography" class="section level1">
<h1><span class="header-section-number">8</span> Demography</h1>
<p><em>In the previous chapters, we have looked at the transmission of information between individuals. We have seen that relatively simple mechanisms at the individual level can lead to population-level outcomes (e.g. the fixation of a rare cultural trait). We have also seen the importance of the characteristics of individuals (e.g. for success and prestige bias) in cultural processes. What we have not yet looked at is how the characteristics of the population may affect the outcome of cultural dynamics. In the following three chapters we will have a closer look at how: population size (demography), population structure (social networks), and group structured populations (with migration) can influence cultural evolution.</em></p>
<div id="background-on-demography-mediated-cultural-loss" class="section level2">
<h2><span class="header-section-number">8.1</span> Background on demography-mediated cultural loss</h2>
<p>Why would demography matter to cultural evolution? As long as information is transmitted among individuals and between generations, the size of the population should not play a role. In theory, this statement is true but it relies on a crucial assumption: information transfer is not only complete (all information from the previous generation is transmitted to the next generation) but also error-free. However, from many lab experiments, we know that copying information is an error-prone process. In this chapter, we will look at how those errors affect information accumulation and how population size is augmenting this process.</p>
<p>Several studies have looked at population effects. <span class="citation">@shennan_demography_2015</span> provide a good overview of a variety of approaches and questions. For example, in their model, <span class="citation">@ghirlanda_sustainability_2010</span>, investigate the interplay between cultural innovations and cultural loss. While it would be trivial to say that culture accumulates where the rate of cultural innovation is higher than the rate of cultural loss, this model allows for two additional complicating mechanisms: (1) it lets innovations affect carrying capacity (and so the number of innovators), and (2) it allows trait corruption (i.e. a trait that was adaptive before can become maladaptive later, e.g. because it allows the over-exploitation of a resource).</p>
<p>Another well-known study is that by Joseph <span class="citation">@henrich_demography_2004</span>. His model takes inspiration from the archaeological record of Tasmania, which shows a deterioration of some and the persistence of other cultural traits after Tasmania was cut-off from Australia at the end of the last ice age. Henrich develops a compelling analytical model to show that the same adaptive processes in cultural evolution can result in the improvement and retention of simple skills but also the deterioration and even loss of complex skills. In the following section, we will take a closer look at this model.</p>
</div>
<div id="the-tasmania-case-model" class="section level2">
<h2><span class="header-section-number">8.2</span> The Tasmania Case model</h2>
<p>The principle idea of Henrich’s model is the following: information transmission from one generation to another (or from one individual to another, here it does not make a difference) has a random component (error rate) that will lead to most individuals failing to achieve the same skill level (denoted with <span class="math inline">\(z\)</span>) as their cultural model, whereas a few will match and - even fewer - exceed that skill level. Imagine a group of students who try to acquire the skills to manufacture a spear. As imitation is imperfect, and memorizing and recalling action sequences is error-prone some students will end up with a spear that is inferior to the one of their cultural model. A few individuals might achieve a similar or even higher skill level than their cultural model. Fig. @ref(fig:henrichGumbel) is showing this principle.</p>
<p>To simulate imperfect imitation, Henrich’s model uses random values from a Gumbel distribution. This distribution is commonly used to model the distribution of extreme (here maximum proficiency) values. Its shape is controlled by two parameters: <span class="math inline">\(\mu\)</span> (location) and <span class="math inline">\(\sigma&gt;0\)</span> (scale, sometimes also denoted as <span class="math inline">\(\beta\)</span>). Varying <span class="math inline">\(\mu\)</span> affects how tricky it is to acquire a given skill. If we subtract an amount <span class="math inline">\(\alpha\)</span> from <span class="math inline">\(\mu\)</span> we move the distribution to the left, and so fewer individuals will acquire a skill level that is larger than that of the cultural model. The larger <span class="math inline">\(\alpha\)</span> the harder it is to acquire a given skill. Varying <span class="math inline">\(\sigma\)</span> on the other hand affects the width of the distribution, and so whether imitators make very similar or systematic mistakes (small <span class="math inline">\(\sigma\)</span>, narrow distribution) or whether errors are very different from each other (large <span class="math inline">\(\sigma\)</span>, wide distribution). By using different values for <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\sigma\)</span>, we can simulate different skill complexity and imperfect imitation. Intuitively, whether the average skill level of a population increases, persists, or decreases depends on how likely it is that some imitators will achieve a skill that exceeds the current cultural model. Additional to the skill complexity, this also depends on how many individuals try to imitate the skill (how many values are drawn from the distribution). The smaller the pool of imitators, the fewer individuals will achieve a higher skill level and so, over time the skill level will decrease. Henrich provides an analytical model to explain how societies below a critical size (of cultural learners) might lose complex (or even simple) cultural skills over time. We will attempt to re-create his results using an individual-based model.</p>
<div class="figure">
<img src="_main_files/figure-html/henrichGumbel-1.png" alt="Shown are the probability distributions to acquire a specific skill level (z, x-axis) for two different skills (a simple one that is easy to learn, and a compelx one that is harder to learn). Given that learning is error-prone more individuals will acquire a skill level that is lower than that of a cultural model (its level is indicated by the vertical dashed line) through imitation (left of the dashed line). A few individauls will achieve higher skill levels (right of the dashed line). For the complex skill the probability to be above the skill level of the cultural model is lower (smaller area under the curve) than for simple skills. For simple skill $\alpha=-5$ and $\sigma=3$ and for complex skill $\alpha=-9$ and $\sigma=2$." width="672" />
<p class="caption">
(#fig:henrichGumbel)Shown are the probability distributions to acquire a specific skill level (z, x-axis) for two different skills (a simple one that is easy to learn, and a compelx one that is harder to learn). Given that learning is error-prone more individuals will acquire a skill level that is lower than that of a cultural model (its level is indicated by the vertical dashed line) through imitation (left of the dashed line). A few individauls will achieve higher skill levels (right of the dashed line). For the complex skill the probability to be above the skill level of the cultural model is lower (smaller area under the curve) than for simple skills. For simple skill <span class="math inline">\(\alpha=-5\)</span> and <span class="math inline">\(\sigma=3\)</span> and for complex skill <span class="math inline">\(\alpha=-9\)</span> and <span class="math inline">\(\sigma=2\)</span>.
</p>
</div>
<div id="modelling-the-tasmania-case" class="section level3">
<h3><span class="header-section-number">8.2.1</span> Modelling the Tasmania Case</h3>
<p>Our model looks like this: we simulate a population with <span class="math inline">\(N\)</span> individuals. Each individual has a skill level <span class="math inline">\(z\)</span>. In each round, we determine the highest skill level in the population, <span class="math inline">\(z_{\text{max}}\)</span>. We will then draw new values of <span class="math inline">\(z\)</span> for each individual in the population. We draw these values from Gumbel distribution where the new mean is the same as the skill level of the most skilled individual minus <span class="math inline">\(\alpha\)</span>, i.e. <span class="math inline">\(\mu = z_{\text{max}} - \alpha\)</span>. To keep track of the simulation we will store the average proficiency <span class="math inline">\(\bar z\)</span> and the change in average proficiency <span class="math inline">\(\Delta \bar z\)</span>.</p>
<p>We begin by loading the packages we will need. We will load the <code>extraDistr</code> package that gives us access to the <code>rgumbel()</code> function, which draws random values from a Gumbel distribution. We will have to define the shape of the distribution by providing two values, <span class="math inline">\(\mu\)</span> (location) and <span class="math inline">\(\sigma\)</span> (scale).</p>
<p>Next, we set the variables that we need to run the simulation, that is, population size <code>N</code>, a vector to store the skill level <code>z</code> for each individual, the number of simulation turns <code>t_max</code>, and the reporting variables <code>z_bar</code> and <code>z_delta_bar</code> for average skill level and the change of the average skill level respectively.</p>
<p>Finally, we write down a very basic learning loop. The first step in this <code>for()</code> loop is to draw new values of <code>z</code> and store them in <code>z_new</code>. We then calculate the mean of the new skill levels and the change compared to the previous time step and finally update all values stored in <code>z</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">library</span>(extraDistr)</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># set population size</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>N &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="co"># draw random values from a uniform distribution to initialise z</span></span>
<span id="cb1-7"><a href="#cb1-7"></a>z &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>, N)</span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="co"># set number of simulation rounds</span></span>
<span id="cb1-9"><a href="#cb1-9"></a>t_max &lt;-<span class="st"> </span><span class="dv">5000</span></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="co"># set up variable to store average z</span></span>
<span id="cb1-11"><a href="#cb1-11"></a>z_bar &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA</span>, t_max)</span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="co"># set up variable to store change in average z</span></span>
<span id="cb1-13"><a href="#cb1-13"></a>z_delta_bar &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA</span>, t_max)</span>
<span id="cb1-14"><a href="#cb1-14"></a></span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="co"># set parameters for Gumbel distribution</span></span>
<span id="cb1-16"><a href="#cb1-16"></a>sigma &lt;-<span class="st"> </span><span class="dv">3</span></span>
<span id="cb1-17"><a href="#cb1-17"></a>alpha &lt;-<span class="st"> </span><span class="dv">5</span></span>
<span id="cb1-18"><a href="#cb1-18"></a></span>
<span id="cb1-19"><a href="#cb1-19"></a><span class="cf">for</span>(r <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>t_max){</span>
<span id="cb1-20"><a href="#cb1-20"></a>  <span class="co"># calculate new z</span></span>
<span id="cb1-21"><a href="#cb1-21"></a>  z_new &lt;-<span class="st"> </span><span class="kw">rgumbel</span>(<span class="dt">n =</span> N, <span class="dt">mu =</span> <span class="kw">max</span>(z) <span class="op">-</span><span class="st"> </span>alpha, <span class="dt">sigma =</span> sigma)</span>
<span id="cb1-22"><a href="#cb1-22"></a>  <span class="co"># record average skill level</span></span>
<span id="cb1-23"><a href="#cb1-23"></a>  z_bar[r] &lt;-<span class="st"> </span><span class="kw">mean</span>(z_new)</span>
<span id="cb1-24"><a href="#cb1-24"></a>  <span class="co"># record average change in z</span></span>
<span id="cb1-25"><a href="#cb1-25"></a>  z_delta_bar[r] &lt;-<span class="st"> </span><span class="kw">mean</span>(z_new <span class="op">-</span><span class="st"> </span>z)</span>
<span id="cb1-26"><a href="#cb1-26"></a>  <span class="co"># update z</span></span>
<span id="cb1-27"><a href="#cb1-27"></a>  z &lt;-<span class="st"> </span>z_new</span>
<span id="cb1-28"><a href="#cb1-28"></a>}</span></code></pre></div>
<p>Let us now plot the result of this simulation run:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>z_delta_bar_val &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(z_delta_bar), <span class="dt">y =</span> z_delta_bar)</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="kw">ggplot</span>(z_delta_bar_val) <span class="op">+</span><span class="st"> </span></span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span></span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;time&quot;</span>) <span class="op">+</span></span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;change in z&quot;</span>) <span class="op">+</span></span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">mean</span>(z_delta_bar_val<span class="op">$</span>y), <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>, <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span></span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<div class="figure">
<img src="_main_files/figure-html/10.3-1.png" alt="While $\bar z$ is sometimes above and sometimes below $0$, it is on average postive (dashed line), which indicated that the average skill level of the population increases." width="672" />
<p class="caption">
(#fig:10.3)While <span class="math inline">\(\bar z\)</span> is sometimes above and sometimes below <span class="math inline">\(0\)</span>, it is on average postive (dashed line), which indicated that the average skill level of the population increases.
</p>
</div>
<p>We find that <span class="math inline">\(\Delta \bar z\)</span> quickly plateaus at about 17.4 (grey dashed line). As this is <span class="math inline">\(&gt;0\)</span>, on average the population will improve its skill over time. We can see that this is the case when we plot the average skill level over time:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>z_bar_val &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(z_bar), <span class="dt">y =</span> z_bar)</span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="kw">ggplot</span>(z_bar_val) <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;time&quot;</span>) <span class="op">+</span></span>
<span id="cb3-5"><a href="#cb3-5"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;average skill-level&quot;</span>) <span class="op">+</span></span>
<span id="cb3-6"><a href="#cb3-6"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<div class="figure">
<img src="_main_files/figure-html/10.4-1.png" alt="For the given parameter ($\alpha=7$, $\sigma=1$) the average skill-level increases continously." width="672" />
<p class="caption">
(#fig:10.4)For the given parameter (<span class="math inline">\(\alpha=7\)</span>, <span class="math inline">\(\sigma=1\)</span>) the average skill-level increases continously.
</p>
</div>
<p>As in the previous chapters, we can now write a wrapper function that allows us to execute this model repeatedly and for different parameters. In the following, we will use a new function: <code>lapply()</code>. There is a series of apply functions in the R programming language that ‘apply’ a function to the elements of a given data object. Generally, these functions take an argument <code>X</code> (a vector, matrix, list, etc.) and then apply the function <code>FUN</code> to each element. We use <code>lapply</code> here on a vector <code>1:R_MAX</code>, that is, a vector of the length of the number of repetitions that we want. What will happen is that <code>lapply()</code> will execute the function that we will provide exactly R_MAX times, and then return the result of each calculation in a list at the end. We could also use a <code>for()</code> loop just as we have done it in the previous chapters. However, the advantage of using the apply function over the loop is that each simulation can run independently from each other. That is because the second simulation does not have to wait for the first to be finished. In contrast, we could not use the apply function for the individual turns. Here the second simulation step <em>does</em> rely on the results of the first step. In this case, all simulation steps have to be calculated in sequence.</p>
<p>Have a look at our <code>demography_model()</code> wrapper function:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>demography_model &lt;-<span class="st"> </span><span class="cf">function</span>(T_MAX, N, ALPHA, SIGMA, R_MAX){</span>
<span id="cb4-2"><a href="#cb4-2"></a>  res &lt;-<span class="st"> </span><span class="kw">lapply</span>(<span class="dv">1</span><span class="op">:</span>R_MAX, <span class="cf">function</span>(repetition){</span>
<span id="cb4-3"><a href="#cb4-3"></a>                  z &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>, N)</span>
<span id="cb4-4"><a href="#cb4-4"></a>                  z_delta_bar &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA</span>, T_MAX)</span>
<span id="cb4-5"><a href="#cb4-5"></a>                  <span class="cf">for</span>(turn <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>T_MAX){</span>
<span id="cb4-6"><a href="#cb4-6"></a>                    z_new &lt;-<span class="st"> </span><span class="kw">rgumbel</span>(<span class="dt">n =</span> N, <span class="dt">mu =</span> <span class="kw">max</span>(z) <span class="op">-</span><span class="st"> </span>ALPHA, <span class="dt">sigma =</span> SIGMA)</span>
<span id="cb4-7"><a href="#cb4-7"></a>                    z_delta_bar[turn] &lt;-<span class="st"> </span><span class="kw">mean</span>(z_new <span class="op">-</span><span class="st"> </span>z)</span>
<span id="cb4-8"><a href="#cb4-8"></a>                    z &lt;-<span class="st"> </span>z_new</span>
<span id="cb4-9"><a href="#cb4-9"></a>                  }</span>
<span id="cb4-10"><a href="#cb4-10"></a>                  <span class="kw">return</span>(<span class="kw">mean</span>(z_delta_bar))</span>
<span id="cb4-11"><a href="#cb4-11"></a>                })</span>
<span id="cb4-12"><a href="#cb4-12"></a>  <span class="kw">mean</span>(<span class="kw">unlist</span>(res))</span>
<span id="cb4-13"><a href="#cb4-13"></a>}</span></code></pre></div>
<p>We begin by initiating a function called <code>demography_model</code> that is taking a set of parameters (note, it can be useful to capitalize arguments of a function to differentiate between those values that are calculated within a function (not capitalized) and those that have been provided with the function call). When we execute <code>demography_model()</code> it will first run an <code>lapply()</code> function for <code>R_MAX</code> number of rounds. The <code>lapply()</code> function will now run independent simulations which we have discussed above (i.e. setting up a population of individuals with skill level <code>z</code>, updating these values, and calculating the change in average skill level). The last step is to calculate the mean of <code>z_delta_bar</code>, i.e. the average of the change of the mean skill level. This is value is calculated for each repetition. <code>lapply()</code> returns all of these values in a list called <code>res</code>. As we are interested in the average change of the skill level across all repetitions, we first turn this list into a vector (using the <code>unlist()</code> function) and then calculate the mean.</p>
<p>Let us now use the <code>demography_model()</code> function, to run repeated simulations for different population sizes and different skill complexity. Here, we use the following parameters for the skill complexities: <span class="math inline">\(\alpha=7, \sigma=1\)</span> (simple) and <span class="math inline">\(\alpha=9, \sigma=1\)</span> (complex).</p>
<p>We first define a variable, <code>sizes</code>, for the different population sizes. We are then again relying on the magic of the <code>lapply()</code> function. As above, the reason is that we can let simulations with different population sizes run independently from each other. Note that we provide <code>sizes</code> as our <code>X</code> argument, and <code>demography_model()</code> as the <code>FUN</code> function argument. Our <code>demography_model()</code> itself requires further arguments to run. In the <code>lapply()</code> function we can simply add them at the end. They will be directly handed over to <code>demography_model()</code> when we execute the <code>lapply()</code> function.</p>
<p>In the last line of this chunk, we create a <code>tibble</code> that will hold the results of the simulations for each skill and the different population sizes.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>sizes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">100</span>, <span class="dt">to =</span> <span class="dv">6100</span>, <span class="dt">by =</span> <span class="dv">500</span>))</span>
<span id="cb5-2"><a href="#cb5-2"></a>sizes</span></code></pre></div>
<pre><code>##  [1]    2  100  600 1100 1600 2100 2600 3100 3600 4100 4600 5100 5600 6100</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>simple_skill &lt;-<span class="st"> </span><span class="kw">lapply</span>(<span class="dt">X=</span>sizes, <span class="dt">FUN=</span>demography_model, </span>
<span id="cb7-2"><a href="#cb7-2"></a>                       <span class="dt">T_MAX =</span> <span class="dv">200</span>, <span class="dt">ALPHA =</span> <span class="dv">7</span>, <span class="dt">SIGMA =</span> <span class="dv">1</span>, <span class="dt">R_MAX =</span> <span class="dv">20</span>)</span>
<span id="cb7-3"><a href="#cb7-3"></a></span>
<span id="cb7-4"><a href="#cb7-4"></a>complex_skill &lt;-<span class="st"> </span><span class="kw">lapply</span>(<span class="dt">X=</span>sizes, <span class="dt">FUN=</span>demography_model, </span>
<span id="cb7-5"><a href="#cb7-5"></a>                        <span class="dt">T_MAX =</span> <span class="dv">200</span>, <span class="dt">ALPHA =</span> <span class="dv">9</span>, <span class="dt">SIGMA =</span> <span class="dv">1</span>, <span class="dt">R_MAX =</span> <span class="dv">20</span>)</span>
<span id="cb7-6"><a href="#cb7-6"></a></span>
<span id="cb7-7"><a href="#cb7-7"></a>data &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">N =</span> <span class="kw">rep</span>(sizes, <span class="dv">2</span>), </span>
<span id="cb7-8"><a href="#cb7-8"></a>               <span class="dt">z_delta_bar =</span> <span class="kw">c</span>(<span class="kw">unlist</span>(simple_skill), </span>
<span id="cb7-9"><a href="#cb7-9"></a>                               <span class="kw">unlist</span>(complex_skill)), </span>
<span id="cb7-10"><a href="#cb7-10"></a>               <span class="dt">skill =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;simple&quot;</span>,<span class="st">&quot;complex&quot;</span>), <span class="dt">each =</span> <span class="kw">length</span>(sizes)))</span></code></pre></div>
<p>Let us now plot the results:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="kw">ggplot</span>(data) <span class="op">+</span><span class="st"> </span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> N, <span class="dt">y =</span> z_delta_bar, <span class="dt">color =</span> skill)) <span class="op">+</span></span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Effective population size&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb8-4"><a href="#cb8-4"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Change in average skill level, delta z bar&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb8-5"><a href="#cb8-5"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb8-6"><a href="#cb8-6"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<div class="figure">
<img src="_main_files/figure-html/effectivePopSize-1.png" alt="For a simple skill effective populaton size (at which the skill can be just maintained in a population) is much smaller than the population that is required to maintain a complext skill." width="672" />
<p class="caption">
(#fig:effectivePopSize)For a simple skill effective populaton size (at which the skill can be just maintained in a population) is much smaller than the population that is required to maintain a complext skill.
</p>
</div>
<p>In Fig. @ref(fig:effectivePopSize) we can see that the simple skill (blue) intercepts the x-axis at much smaller population sizes than the complex skill. That means, a simple skill can be maintained by much smaller populations, whereas larger populations of imitators are required for complex skills.</p>
</div>
<div id="calculating-critical-population-sizes-based-on-skill-complexity" class="section level3">
<h3><span class="header-section-number">8.2.2</span> Calculating critical population sizes based on skill complexity</h3>
<p>Henrich calls the minimum population size required to maintain a skill the critical population size, <span class="math inline">\(N^\star\)</span>. How can we calculate <span class="math inline">\(N^\star\)</span> for different skill complexities? We could run simulations for many more population sizes and find the one where <span class="math inline">\(\Delta \bar z\)</span> is closest to zero. Alternatively, here is a more elegant and less computationally intensive method: when we plot our results over logarithmic population size the resulting graphs are almost linear (see @ref(fig:logEffectivePopSize)).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="kw">ggplot</span>(data) <span class="op">+</span><span class="st"> </span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">log</span>(N), <span class="dt">y =</span> z_delta_bar, <span class="dt">color=</span>skill)) <span class="op">+</span></span>
<span id="cb9-3"><a href="#cb9-3"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;log(Effective population size)&quot;</span>) <span class="op">+</span></span>
<span id="cb9-4"><a href="#cb9-4"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Change in average skill level, delta z bar&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb9-5"><a href="#cb9-5"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb9-6"><a href="#cb9-6"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<div class="figure">
<img src="_main_files/figure-html/logEffectivePopSize-1.png" alt="The same as in Fig. \@ref(fig:effectivePopSize) but using log on population sizes." width="672" />
<p class="caption">
(#fig:logEffectivePopSize)The same as in Fig. @ref(fig:effectivePopSize) but using log on population sizes.
</p>
</div>
<p>And so, we could use a linear fit and then solve for <span class="math inline">\(y = 0\)</span> to calculate <span class="math inline">\(N^\star\)</span>:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> z_delta_bar <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(N), </span>
<span id="cb10-2"><a href="#cb10-2"></a>          <span class="dt">data =</span> data[data<span class="op">$</span>skill<span class="op">==</span><span class="st">&quot;simple&quot;</span>,])</span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="kw">print</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = z_delta_bar ~ log(N), data = data[data$skill == 
##     &quot;simple&quot;, ])
## 
## Coefficients:
## (Intercept)       log(N)  
##      -6.462        1.001</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>N_star_simple &lt;-<span class="st"> </span><span class="kw">exp</span>(<span class="kw">solve</span>(<span class="kw">coef</span>(fit)[<span class="op">-</span><span class="dv">1</span>], <span class="op">-</span><span class="kw">coef</span>(fit)[<span class="dv">1</span>]))</span>
<span id="cb12-2"><a href="#cb12-2"></a>N_star_simple</span></code></pre></div>
<pre><code>## [1] 637.4271</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> z_delta_bar <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(N), </span>
<span id="cb14-2"><a href="#cb14-2"></a>          <span class="dt">data =</span> data[data<span class="op">$</span>skill<span class="op">==</span><span class="st">&quot;complex&quot;</span>,])</span>
<span id="cb14-3"><a href="#cb14-3"></a>N_star_complex &lt;-<span class="st"> </span><span class="kw">exp</span>(<span class="kw">solve</span>(<span class="kw">coef</span>(fit)[<span class="op">-</span><span class="dv">1</span>], <span class="op">-</span><span class="kw">coef</span>(fit)[<span class="dv">1</span>]))</span>
<span id="cb14-4"><a href="#cb14-4"></a>N_star_complex</span></code></pre></div>
<pre><code>## [1] 4739.841</code></pre>
<p>Note that we need to take the exponent of the resulting value to revert the log function. We see that a simple skill with a low alpha to sigma ratio requires a minimum population size of about 637, whereas a much large population size is required to maintain a complex trait (here 4740).</p>
<p>Let us now calculate the <span class="math inline">\(N^\star\)</span> values for different skill complexities and different population sizes. We first set up the parameter space (all possible combinations of population sizes <span class="math inline">\(N\)</span> and skill complexity, which we will vary using different values for <span class="math inline">\(\alpha\)</span>):</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># run simulation for the following population sizes</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>sizes &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">100</span>, <span class="dt">to =</span> <span class="dv">6100</span>, <span class="dt">by =</span> <span class="dv">500</span>)</span>
<span id="cb16-3"><a href="#cb16-3"></a></span>
<span id="cb16-4"><a href="#cb16-4"></a><span class="co"># run simulation for the following values of alpha</span></span>
<span id="cb16-5"><a href="#cb16-5"></a>alphas &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">4</span>, <span class="dt">to =</span> <span class="dv">9</span>, <span class="dt">by =</span> <span class="fl">.5</span>)</span>
<span id="cb16-6"><a href="#cb16-6"></a></span>
<span id="cb16-7"><a href="#cb16-7"></a>simulations &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(<span class="dt">N =</span> sizes, <span class="dt">alpha =</span> alphas)</span>
<span id="cb16-8"><a href="#cb16-8"></a><span class="kw">head</span>(simulations)</span></code></pre></div>
<pre><code>##      N alpha
## 1  100     4
## 2  600     4
## 3 1100     4
## 4 1600     4
## 5 2100     4
## 6 2600     4</code></pre>
<p>Now we can run simulations for all combinations of population sizes and skill compexities:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>z_delta_bar &lt;-<span class="st"> </span><span class="kw">lapply</span>(<span class="dt">X=</span><span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(simulations), <span class="dt">FUN=</span><span class="cf">function</span>(s){</span>
<span id="cb18-2"><a href="#cb18-2"></a>                  <span class="kw">demography_model</span>(<span class="dt">T_MAX =</span> <span class="dv">200</span>, </span>
<span id="cb18-3"><a href="#cb18-3"></a>                                   <span class="dt">N =</span> simulations[s, <span class="st">&quot;N&quot;</span>], </span>
<span id="cb18-4"><a href="#cb18-4"></a>                                   <span class="dt">ALPHA =</span> simulations[s, <span class="st">&quot;alpha&quot;</span>], </span>
<span id="cb18-5"><a href="#cb18-5"></a>                                   <span class="dt">SIGMA =</span> <span class="dv">1</span>, </span>
<span id="cb18-6"><a href="#cb18-6"></a>                                   <span class="dt">R_MAX =</span> <span class="dv">5</span>)</span>
<span id="cb18-7"><a href="#cb18-7"></a>  })</span>
<span id="cb18-8"><a href="#cb18-8"></a><span class="co"># add results to population size and skill complexity</span></span>
<span id="cb18-9"><a href="#cb18-9"></a>data &lt;-<span class="st"> </span><span class="kw">cbind</span>(simulations, <span class="dt">z_delta_bar=</span><span class="kw">unlist</span>(z_delta_bar))</span>
<span id="cb18-10"><a href="#cb18-10"></a><span class="kw">head</span>(data)</span></code></pre></div>
<pre><code>##      N alpha z_delta_bar
## 1  100     4    1.194446
## 2  600     4    2.926911
## 3 1100     4    3.557935
## 4 1600     4    3.879509
## 5 2100     4    4.167676
## 6 2600     4    4.390780</code></pre>
<p>Finally, let us fit a linear regression to each skill complexity to determine the according critical population size <span class="math inline">\(N^\star\)</span>:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>n_stars &lt;-<span class="st"> </span><span class="kw">lapply</span>(<span class="dt">X =</span> <span class="kw">unique</span>(data<span class="op">$</span>alpha), <span class="dt">FUN =</span> <span class="cf">function</span>(alpha){</span>
<span id="cb20-2"><a href="#cb20-2"></a>                      <span class="co"># only use the results with identical value for alpha</span></span>
<span id="cb20-3"><a href="#cb20-3"></a>                      subset &lt;-<span class="st"> </span>data[data<span class="op">$</span>alpha<span class="op">==</span>alpha,]</span>
<span id="cb20-4"><a href="#cb20-4"></a>                      <span class="co"># fit regression</span></span>
<span id="cb20-5"><a href="#cb20-5"></a>                      fit &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> z_delta_bar <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(N), <span class="dt">data =</span> subset)</span>
<span id="cb20-6"><a href="#cb20-6"></a>                      <span class="co"># solve for n star</span></span>
<span id="cb20-7"><a href="#cb20-7"></a>                      n_star &lt;-<span class="st"> </span><span class="kw">exp</span>(<span class="kw">solve</span>(<span class="kw">coef</span>(fit)[<span class="op">-</span><span class="dv">1</span>], <span class="op">-</span><span class="kw">coef</span>(fit)[<span class="dv">1</span>]))</span>
<span id="cb20-8"><a href="#cb20-8"></a>                      <span class="kw">return</span>(n_star)</span>
<span id="cb20-9"><a href="#cb20-9"></a>                    })</span>
<span id="cb20-10"><a href="#cb20-10"></a><span class="co"># combine all results in a single tibble</span></span>
<span id="cb20-11"><a href="#cb20-11"></a>results &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">n_star =</span> <span class="kw">unlist</span>(n_stars), <span class="dt">alpha =</span> <span class="kw">unique</span>(data<span class="op">$</span>alpha))</span>
<span id="cb20-12"><a href="#cb20-12"></a>results</span></code></pre></div>
<pre><code>## # A tibble: 11 x 2
##    n_star alpha
##     &lt;dbl&gt; &lt;dbl&gt;
##  1   30.3   4  
##  2   48.9   4.5
##  3   83.9   5  
##  4  143.    5.5
##  5  231.    6  
##  6  376.    6.5
##  7  633.    7  
##  8 1043.    7.5
##  9 1715.    8  
## 10 2885.    8.5
## 11 4826.    9</code></pre>
<p>Now, we plot the critical population size as a function of the skill complexity <span class="math inline">\(\alpha\)</span> over <span class="math inline">\(\sigma\)</span>:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="kw">ggplot</span>(results, <span class="kw">aes</span>(<span class="dt">x =</span> alpha, <span class="dt">y =</span> n_star)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(alpha<span class="op">/</span>sigma)) <span class="op">+</span></span>
<span id="cb22-4"><a href="#cb22-4"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Critical populaton size, N*&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb22-5"><a href="#cb22-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<div class="figure">
<img src="_main_files/figure-html/10.13-1.png" alt="The critical population size, $N^\star$, increases exponentially as skill complexity increases." width="672" />
<p class="caption">
(#fig:10.13)The critical population size, <span class="math inline">\(N^\star\)</span>, increases exponentially as skill complexity increases.
</p>
</div>
<p>It is interesting to observe that the critical population size increases exponentially with skill complexity. This also suggests that all being equal, very high skill levels will never be reached by finite population sizes. However, different ways of learning (e.g. teaching) could considerably decrease <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\sigma\)</span> over time and so allow high skill levels.</p>
</div>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">8.3</span> Summary of the model</h2>
<p>Similar to the model in the chapter on Rogers’ paradox, the present model is very simple and is making many simplifications. Nevertheless, it provides an intuitive understanding of how changes (up and down) in population size can affect the cultural repertoire of a population, and how it can be that simple skills thrive, while complex ones disappear. In the next chapter, we will discuss the importance of social networks, i.e. who can interact with whom. We will see that this will also have an effect (additional to the population size).</p>
</div>
<div id="further-readings" class="section level2">
<h2><span class="header-section-number">8.4</span> Further readings</h2>
<p><span class="citation">@henrich_demography_2004</span> provides a detailed analytical model. <span class="citation">@powell_late_2009</span> provide an extension to Henrich’s model by incorporating subpopulations with varying density. <span class="citation">@shennan_demography_2001</span> is another modeling paper that suggests that innovations are far more successful in larger compared to smaller populations. There is also an increasing number of empirical studies reporting population size effects, for example, on the number of folk tale types <span class="citation">@acerbi_cultural_2017</span>.</p>
<!--chapter:end:10-Demography.Rmd-->
</div>
</div>
<div id="social-network-structure" class="section level1">
<h1><span class="header-section-number">9</span> Social network structure</h1>
<p>Placeholder</p>
<div id="network-basics" class="section level2">
<h2><span class="header-section-number">9.1</span> Network basics</h2>
</div>
<div id="plotting-networks" class="section level2">
<h2><span class="header-section-number">9.2</span> Plotting networks</h2>
</div>
<div id="analyse-social-networks" class="section level2">
<h2><span class="header-section-number">9.3</span> Analyse social networks</h2>
<div id="network-properties" class="section level3">
<h3><span class="header-section-number">9.3.1</span> Network properties</h3>
</div>
<div id="vertex-properties" class="section level3">
<h3><span class="header-section-number">9.3.2</span> Vertex properties</h3>
</div>
</div>
<div id="using-social-networks-to-model-information-transmission" class="section level2">
<h2><span class="header-section-number">9.4</span> Using social networks to model information transmission</h2>
<div id="gossip-transmission-on-networked-populations" class="section level3">
<h3><span class="header-section-number">9.4.1</span> Gossip transmission on networked populations</h3>
</div>
<div id="how-does-network-structure-affect-information-transmission" class="section level3">
<h3><span class="header-section-number">9.4.2</span> How does network structure affect information transmission?</h3>
</div>
<div id="complex-versus-simple-contagion" class="section level3">
<h3><span class="header-section-number">9.4.3</span> Complex versus simple contagion</h3>
</div>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">9.5</span> Summary of the model</h2>
</div>
<div id="further-reading" class="section level2">
<h2><span class="header-section-number">9.6</span> Further Reading</h2>
<!--chapter:end:11-Social_network_structure.Rmd-->
</div>
</div>
<div id="group-structured-populations-and-migration" class="section level1">
<h1><span class="header-section-number">10</span> Group structured populations and migration</h1>
<p>Placeholder</p>
<div id="modelling-migration" class="section level2">
<h2><span class="header-section-number">10.1</span> Modelling migration</h2>
</div>
<div id="subdivided-population" class="section level2">
<h2><span class="header-section-number">10.2</span> Subdivided population</h2>
</div>
<div id="simulating-migration-between-sub-populations" class="section level2">
<h2><span class="header-section-number">10.3</span> Simulating migration between sub-populations</h2>
</div>
<div id="varying-the-strength-of-migration-for-repeated-simulation-runs" class="section level2">
<h2><span class="header-section-number">10.4</span> Varying the strength of migration for repeated simulation runs</h2>
</div>
<div id="model-extensions" class="section level2">
<h2><span class="header-section-number">10.5</span> Model extensions</h2>
<div id="innovation-or-mutation" class="section level3 unnumbered">
<h3>Innovation or mutation</h3>
</div>
<div id="copy-m-models" class="section level3 unnumbered">
<h3>Copy <span class="math inline">\(m\)</span> models</h3>
</div>
<div id="learn-from-but-not-moving-to-another-sub-population" class="section level3 unnumbered">
<h3>Learn from but not moving to another sub-population</h3>
</div>
<div id="variable-migration-probability-among-sub-populations" class="section level3 unnumbered">
<h3>Variable migration probability among sub-populations</h3>
</div>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">10.6</span> Summary of the model</h2>
</div>
<div id="further-reading" class="section level2">
<h2><span class="header-section-number">10.7</span> Further reading</h2>
<!--chapter:end:12-Group_structure_populations_and_migration.Rmd-->
</div>
</div>
<div id="part-advanced-topics---cultural-inheritance" class="section level1 unnumbered">
<h1>(PART*) Advanced topics - Cultural inheritance</h1>
<p>Placeholder</p>
<div id="copying-and-selection" class="section level2">
<h2><span class="header-section-number">10.8</span> Copying and selection</h2>
</div>
<div id="convergent-transformation" class="section level2">
<h2><span class="header-section-number">10.9</span> Convergent transformation</h2>
</div>
<div id="emergent-similarity" class="section level2">
<h2><span class="header-section-number">10.10</span> Emergent similarity</h2>
</div>
<div id="cultural-fitness" class="section level2">
<h2><span class="header-section-number">10.11</span> Cultural fitness</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">10.12</span> Summary of the model</h2>
</div>
<div id="further-readings" class="section level2">
<h2><span class="header-section-number">10.13</span> Further readings</h2>
<!--chapter:end:13-Reproduction_and_transformation.Rmd-->
</div>
</div>
<div id="social-learning-of-social-learning-rules" class="section level1">
<h1><span class="header-section-number">11</span> Social learning of social learning rules</h1>
<p>Placeholder</p>
<div id="openness-and-conservatism" class="section level2">
<h2><span class="header-section-number">11.1</span> Openness and conservatism</h2>
</div>
<div id="maintaining-open-populations" class="section level2">
<h2><span class="header-section-number">11.2</span> Maintaining open populations</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">11.3</span> Summary of the model</h2>
</div>
<div id="further-readings" class="section level2">
<h2><span class="header-section-number">11.4</span> Further readings</h2>
<!--chapter:end:14-Social_learning_of_social_learning_rules.Rmd-->
</div>
</div>
<div id="traits-inter-dependence" class="section level1">
<h1><span class="header-section-number">12</span> Traits inter-dependence</h1>
<p>Placeholder</p>
<div id="compatible-and-incompatible-traits" class="section level2">
<h2><span class="header-section-number">12.1</span> Compatible and incompatible traits</h2>
</div>
<div id="many-traits-model" class="section level2">
<h2><span class="header-section-number">12.2</span> Many-traits model</h2>
</div>
<div id="summary-of-the-model" class="section level2">
<h2><span class="header-section-number">12.3</span> Summary of the model</h2>
</div>
<div id="further-readings" class="section level2">
<h2><span class="header-section-number">12.4</span> Further readings</h2>
<!--chapter:end:15-Traits_inter-dependence.Rmd-->
</div>
</div>
<div id="Introduction" class="section level1 unnumbered">
<h1>Introduction</h1>
<p>Placeholder</p>
<div id="aim-of-the-book" class="section level2">
<h2><span class="header-section-number">12.5</span> Aim of the book</h2>
</div>
<div id="what-is-cultural-evolution" class="section level2">
<h2><span class="header-section-number">12.6</span> What is cultural evolution?</h2>
</div>
<div id="why-model" class="section level2">
<h2><span class="header-section-number">12.7</span> Why model?</h2>
</div>
<div id="why-individual-based-models" class="section level2">
<h2><span class="header-section-number">12.8</span> Why individual-based models?</h2>
</div>
<div id="how-to-use-this-book" class="section level2">
<h2><span class="header-section-number">12.9</span> How to use this book</h2>
</div>
<div id="conventions-and-formatting" class="section level2">
<h2><span class="header-section-number">12.10</span> Conventions and formatting</h2>
<!--chapter:end:Index.Rmd-->
</div>
</div>
<!--bookdown:body:end-->
            </section>

          </div>
        </div>
      </div>
<!--bookdown:link_prev-->
<!--bookdown:link_next-->
    </div>
  </div>
<!--bookdown:config-->

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
