--- 
title: "Individual-based models of cultural evolution"
subtitle: "A step-by-step guide using R"
author: 
- Alberto Acerbi
- Alex Mesoudi
- Marco Smolla
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: "biblio.bib"
link-citations: true
---

# Introduction {-#Introduction}

## Aim of the book

The field of cultural evolution has emerged in the last few decades as a thriving, interdisciplinary effort to understand cultural change and cultural diversity within an evolutionary framework and using evolutionary tools, concepts and methods. Given its roots in evolutionary biology, much of cultural evolution is grounded in, or inspired by, formal models. Yet many researchers interested in cultural evolution come from backgrounds that lack training in formal models, such as psychology, anthropology or archaeology.

The aim of this book is to partly address this gap by showing readers how to create Individual Based Models (IBMs, also known as Agent-Based Models) of cultural evolution. We provide example code written in the programming language R, which has found widespread adoption in the scientific community. We will go from very simple models of the basic processes of cultural evolution, such as biased transmission and cultural mutation, to more advanced topics such as the evolution of social learning, demographic effects, and social network analysis. Where possible we recreate existing models in the literature, so that readers can better understand those existing models, and perhaps even extend them to address questions of their own interest.

## What is cultural evolution?

The theory of evolution is typically applied to genetic change. Darwin pointed out that the diversity and complexity of living things can be explained in terms of a deceptively simple process: (1) organisms vary in their characteristics, (2) these characteristics are inherited from parent to offspring, and (3) those characteristics that make an organism more likely to survive and reproduce will tend to increase in frequency over time. That's pretty much it. Since Darwin, biologists have filled in many of the details of this abstract idea. Geneticists have shown that heritable 'characteristics' are determined by genes, and worked out where genetic variation comes from (e.g. mutation, recombination) and how genetic inheritance works (e.g. via Mendel's laws, and DNA). The details of selection have been explored, revealing the many reasons why some genes spread and others don't. Others realised that not all biological change results from selection, it can also result from random processes like population bottlenecks (genetic drift).

The theory of cultural evolution rests on the observation that culture constitutes a similar evolutionary process to that outlined above. By 'culture' we mean information that passes from one individual to another socially, rather than genetically. This could include things we colloquially call knowledge, beliefs, ideas, attitudes, customs, words, or values. These are all learned from others via various 'social learning' mechanisms such as imitation or spoken/written language. The key point is that social learning is an inheritance system. Cultural characteristics (or cultural traits) vary across individuals, they are passed from individual to individual, and in many cases some traits are more likely to spread than others. This is Darwin's insight, applied to culture. Cultural evolution researchers think that we can use similar evolutionary concepts, tools and methods to explain the diversity and complexity of culture, just as biologists have done for the diversity and complexity of living forms.

Importantly, we do not need to assume that cultural evolution is identical to genetic evolution. Many of the details will be different. To take an obvious example, we get DNA only from our two parents, but we can get ideas from many sources: teachers, strangers on the internet, long-dead authors' books, or even our parents. Cultural evolution researchers seek to build models and do research to fill in these details. The models in this book will help you to understand many of the above principles, by creating simulations of various aspects of cultural evolution.


## Why model?

A formal model is a simplified version of reality, written in mathematical equations or computer code. Formal models are useful because reality is complex. We can observe changes in species or cultures over time, or particular patterns of biological or cultural diversity, but there are always a vast array of possible causes for any particular pattern or trend, and huge numbers of variables interacting in many different ways. A formal model is a highly simplified recreation of a small part of this complex reality, containing a few elements or processes that the modeller suspects are important. A model, unlike reality, can be manipulated and probed in order to better understand how each part works. No model is ever a complete recreation of reality. That would be pointless: we would have replaced a complex, incomprehensible reality with a complex, incomprehensible model. Instead, models are useful *because* of their simplicity.

Formal modelling is rare in the social sciences (with some exceptions, such as economics). Social scientists tend to be sceptical that very simple models can tell us anything useful about something as immensely complex as human culture. But the clear lesson from biology is that models are extremely useful in precisely this situation. Biologists face similarly immense complexity in the natural world. Despite this, models are useful. Population genetics models of the early 20th century helped to reconcile new findings in genetics with Darwin's theory of evolution. Ecological models helped understand interactions between species, such as predator-prey cycles. These models are hugely simplified: population genetics models typically make ridiculous assumptions like infinitely large populations and random mating. But they are useful because they precisely specify each part of a complex system, improving understanding of reality.

Another way to look at it is that all social scientists use models, but only some use *formal* models. Most models are verbal models, written in words. The problem is that words can be imprecise, and verbal models contain all kinds of hidden or unstated assumptions. The advantage of formal modelling is that we are forced to precisely specify every element and process that we propose, and make all of our assumptions explicit. Maths and code do not accept any ambiguity: they must be told absolutely everything.  For more on the virtues of formal models for social scientists, see Paul Smaldino's 'Models are stupid, and we need more of them' (2017).

## Why individual-based models?

Formal models can be divided in those that are analytically tractable and those that are not. The former are mathematical models that consist of sets of equations that can be solved to find specific answers (e.g. equilibria points). A big advantage of these models is that they can provide insight into the dynamics of a system for a wide range of parameters, or exact results for specific questions. However, this approach requires the studied dynamics to be rather simple. The limits of analytically tractable models are reached when, for example, if individuals differ in their characteristics, interact in a complex, non-linear, or discrete manner, exhibit learning or adaptation, or are embedded in social networks. For these situations, a different kind of model can be useful: Individual-Based Models (IBMs). These models allow a much greater flexibility than mathematical models. Due to their structure they are also often more intuitive to understand, especially for people with little training in mathematics.

The goal of IBMs is to gain insight into the collective behaviour of individuals that follow simple rules. To that end, we create *individuals* (an 'individual' here is often what we colloquially mean by the term 'individual', i.e. a person, but it might also be a cultural trait, or group of individuals like an organisation or country), specify *rules* by which those individuals interact or change over time (e.g. that they learn from one another in certain ways), and *simulate* what happens in our population of individuals over time. 

The strength of IBMs are modularity (individuals can easily be added or removed, and individual rules can be changed without changing the entire model), complexity (individual-level inteactions can be complex and change in responds to other individuals or the environment), and emergence (local interactions can lead to global patterns). However, it is also important to be aware of the downsides of IBMs. For example, generalisations are often not possible and statements only hold for parameters (or sets thereof) that have been simulated. Another potential downside is that the high flexibility of IBMs can quickly lead to models that are *too* complex, and it can be hard to understand what is happening inside the model. That's why, hopefully, our IBMs are simple enough to understand, and provide a gateway into cultural evolution modelling.

## How to use this book

All of the code in this book is written in R (R Core Team 2020). Originally R had a strong focus on statistical data analysis. Its growing user-base has turned R into a more general-purpose programming language. It is therefore widely taught in many university departments and is the subject of lots of online tutorials and support forums.

We have used the [bookdown](https://bookdown.org) package to create an html version of the book, which you may well be reading now. This is created from RMarkdown (.Rmd) files, which are a mix of regular text and code. We also provide just the code, in chunks, as an R script (.R) file. As a reader, you can therefore read the online book and, alongside, run the code using either the Rmd file or the R script. Of course you can just read the book, but running the code as you go will give you more direct experience of how the code executes, and will allow you to play around with parameters and commands. The best way of learning is to try it out yourself!

We assume that the reader has basic knowledge of R (and RStudio, which provides a powerful user-interface for R), including installing it, setting it up, updating it, installing packages and running code. We also assume you have basic knowledge of R as a programming language, e.g. the use of variables, dataframes, functions, subsetting and loops. If not, *Hands On Programming With R* by Garrett Grolemund is a good introduction.

We also use [the tidyverse package](https://www.tidyverse.org), including tibbles (rather than dataframes) and ggplot (rather than the base R plot function). These are user-friendly and widely used, and will make it easier to manipulate data and create professional-looking visualisations. 


## Conventions and formatting

**NEED TO REWRITE THE BELOW AFTER WE DECIDE ON CONVENTIONS - I HAVE NOT CHANGED IT SO FAR**


In general, I'd try to follow the [tidyverse style guide](https://style.tidyverse.org) for names of functions, variables, code, just to be consistent. There is also a [library](https://www.tidyverse.org/articles/2017/12/styler-1.0.0/) that formats automatically the code according to the style guide, and it can be accessed in R Studio from the "Addins" menu ("Style active file"). Of course, it formats things like spaces or tabs and not names or the Rmarkdown text.

For the text, I did so far as such:

* inline code: `geom_line()`, `unbiased_transmission()` (this is standard markdown)

* technical terms: 'geoms', 'chr'

* names of variables: $p$, $generation$ (latex style, works in Rmarkdown)

* names of data structures: **population**, **output** (in **bold**, since if in *italics* they look like names of variables)

Let's add here other options, or discuss if you prefer something else.

